#!/usr/bin/env bash
# Static integrity checks over the markdown that IS this plugin.
#
# Run:  bash scripts/skills-lint.sh [--base <git-ref>]
# Exit: 0 clean, 1 findings, 2 usage/environment error.
#
# WHY THIS EXISTS
# ---------------
# This repo tests its scaffolding rigorously and its product not at all.
# scripts-test.yml runs mutation-checked suites over two shell files under two
# timezones with shellcheck. The ~30 markdown files that are the actual plugin
# got one gate: `claude plugin validate`, a JSON-schema check on plugin.json.
#
# PR #166 is what that costs. In one change: a link-resolution script was
# hand-rolled, run once and thrown away; four gates were renumbered, requiring
# 14 citations remapped across six files, with the recurrence risk mitigated by
# WRITING A PARAGRAPH IN CLAUDE.md; and a behavioural claim shipped unverified.
#
# A paragraph is the weakest enforcement mechanism that exists. CLAUDE.md line
# 31 has stated the ../../shared/ rule for role-skill `references/` files since
# before this script -- and three files violated it anyway, with nine broken
# load paths sitting on main. Check 1 found them. That is the whole argument.
#
# WHAT IT DOES NOT DO
# -------------------
# Nothing here executes a skill or judges its behaviour. These are static,
# deterministic, offline checks -- cheap enough to gate every PR. Behavioural
# evaluation is Tier 2 (see evals/README.md) and runs nightly, because it costs
# API calls and wall-clock that a per-PR gate should not.
#
# ON THE SKIP FLAG
# ----------------
# SKILLS_LINT_SKIP exists for the mutation harness in skills-lint.test.sh, which
# proves every check is load-bearing by disabling each in turn and asserting the
# suite goes red. A check nothing would notice the absence of is a check that
# buys nothing. It is deliberately not a documented user-facing knob: the way to
# silence a finding is to fix it, or to allowlist it with a reason and an issue.

# shellcheck disable=SC2016  # backticks in single quotes are literal markdown, not substitution
set -uo pipefail

ROOT="${SKILLS_LINT_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
BASE=""
SKIP="${SKILLS_LINT_SKIP:-}"

while [ $# -gt 0 ]; do
  case "$1" in
    --base) BASE="${2:-}"; shift 2 || { echo "--base needs a git ref" >&2; exit 2; } ;;
    --help|-h) sed -n '2,4p' "${BASH_SOURCE[0]}"; exit 0 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

cd "$ROOT" || { echo "cannot cd to $ROOT" >&2; exit 2; }

FINDINGS=0
finding() {  # $1 = check id, $2 = file:line or file, $3 = message
  printf '%s  %s: %s\n' "[$1]" "$2" "$3"
  FINDINGS=$((FINDINGS + 1))
}
skipped() { case ",$SKIP," in *",$1,"*) return 0 ;; *) return 1 ;; esac; }

# Files that ship as part of the plugin's behaviour or its public documentation.
#
# docs/plans, docs/brainstorms, docs/solutions and docs/ideation are excluded as
# historical record -- they document what was decided at the time and are never
# retro-edited, so a stale path in them is accurate, not broken. CHANGELOG.md is
# generated by release-please.
_shipped_md() {
  git -C "$ROOT" ls-files '*.md' 2>/dev/null \
    | grep -vE '^(docs/(plans|brainstorms|solutions|ideation)/|CHANGELOG\.md$)'
}

# Live surfaces: everything Claude actually loads at runtime, plus the root docs
# that instruct contributors. Distinguished from docs/adr/ because an ADR is a
# decision record -- its inline path citations describe the repo as it stood at
# decision time, and ADR-0003 deliberately still names skills/shared/tension-triage.md,
# renamed in #166. Rewriting that would falsify the record, so backticked paths
# inside docs/adr/ are out of scope for check 1. Their MARKDOWN LINKS are still
# checked, because a link is navigation and navigation must work.
_live_md() {
  git -C "$ROOT" ls-files 'commands/*.md' 'agents/*.md' 'skills/*.md' \
      'skills/**/*.md' 'README.md' 'CLAUDE.md' 'CONCEPTS.md' 'STRATEGY.md' 2>/dev/null
}

# An allowlist entry is `<citing-file> <path> <reason>`; blanks and # ignored.
#
# Keyed on the PAIR, never on the path alone. `../shared/authority-boundaries.md`
# is a legitimate thing for CLAUDE.md to write -- that sentence defines the path
# convention -- and simultaneously a real bug in a role skill's references/ file.
# A path-only allowlist would silence the second while excusing the first, which
# is how an allowlist quietly becomes a blindfold.
# Read once at startup rather than per candidate: the checks below iterate every
# line of every shipped file, and re-opening the allowlist inside that loop is
# both wasteful and the thing that makes shellcheck (correctly) suspicious about
# nested redirections from a file being read.
ALLOW_PATHS="$(grep -vE '^\s*(#|$)' "$ROOT/evals/lint-allow-paths.txt" 2>/dev/null || true)"

_allowed() {  # $1 = citing file, $2 = candidate path
  local src pat rest
  while read -r src pat rest; do
    [ -n "$src" ] || continue
    [ "$src" = "$1" ] && [ "$pat" = "$2" ] && return 0
  done <<< "$ALLOW_PATHS"
  return 1
}

# ---------------------------------------------------------------------------
# Check 1 -- every path a reader could follow actually resolves.
#
# Two populations, deliberately different in scope:
#
#   markdown links  ](path.md)      navigation; checked in every shipped file
#   backticked path `dir/file.md`   a load instruction; checked in live surfaces
#
# Resolution is STRICT: the citing file's own directory, or the repo root. Not
# "any plausible base". A permissive multi-base resolver would have accepted
# `../shared/agentic-routines.md` inside skills/holacracy-secretary/references/
# -- which resolves from the SKILL root but not from the file doing the loading,
# and is therefore exactly the bug CLAUDE.md line 31 warns about. Being strict
# is what makes this check able to find that class of defect at all.
#
# Bare filenames with no slash are skipped: `SKILL.md` in prose means the
# concept, not a path.
# ---------------------------------------------------------------------------
# One `grep -oEn` pass per file, not a bash loop over lines. The line-at-a-time
# version spawned two subprocesses per line and took 45s over this repo; a
# per-PR gate that slow gets moved to nightly, and then it stops catching things
# before merge, which is the entire point of it.
check_links() {
  skipped 1 && return 0
  local f d hit n target

  while IFS= read -r f; do
    [ -n "$f" ] || continue
    d="$(dirname "$f")"
    while IFS= read -r hit; do
      n="${hit%%:*}"
      target="${hit#*:}"
      target="${target#](}"; target="${target%)}"; target="${target%%#*}"
      case "$target" in http*|mailto*|'') continue ;; esac
      [ -e "$d/$target" ] || [ -e "$target" ] \
        || finding 1 "$f:$n" "markdown link does not resolve: $target"
    done < <(grep -oEn '\]\([^)]+\.md[^)]*\)' "$f" 2>/dev/null)
  done < <(_shipped_md)

  while IFS= read -r f; do
    [ -n "$f" ] || continue
    d="$(dirname "$f")"
    while IFS= read -r hit; do
      n="${hit%%:*}"
      target="${hit#*:}"
      target="${target//\`/}"
      case "$target" in */*) ;; *) continue ;; esac
      [ -e "$d/$target" ] || [ -e "$target" ] && continue
      _allowed "$f" "$target" \
        || finding 1 "$f:$n" "backticked path does not resolve from this file: $target"
    done < <(grep -oEn '`[A-Za-z0-9_./-]+\.md`' "$f" 2>/dev/null)
  done < <(_live_md)
}

# ---------------------------------------------------------------------------
# Check 2 -- a cited step number names a heading that exists.
#
# This is #166's hazard made mechanical. Promoting the authority gate to Step 1
# in skills/shared/triage-gates.md shifted every one of the original four steps,
# and 14 citations across six files had to be remapped BY HAND. Nothing would
# have caught a miss. The mitigation shipped in that PR was a warning paragraph.
#
# A citation is `<path>.md` followed CLOSELY by "Step N" or "Steps N-M". Three
# narrowing rules, each earned by a false positive on the first run:
#
#   40-char window   `../shared/actor-and-role-resolution.md` | At the start of
#                    every Facilitator session (Step 0.5) -- that "Step" is a
#                    session phase 43 chars away, not a citation into the file.
#
#   stop at a
#   sentence break   "Runs `./triage-gates.md` Step 4 (supersession). For
#                    `session` scope, reads the cache populated at Step 7."
#                    Step 4 cites triage-gates; Step 7 is this file's own step.
#                    Binding both to the path was the bug.
#
#   decimals are
#   not steps        "Step 0.5" is a phase label. `Step N` must not be followed
#                    by a dot-digit.
#
# Targets with no `## Step` headings at all are skipped, not failed. Commands
# express their procedure as a numbered list ("`commands/stalled-project-sweep.md`
# step 4"), and this check cannot verify a list item. Better to cover the files
# that use the heading convention honestly than to force a convention on files
# that never adopted it.
# ---------------------------------------------------------------------------
check_step_citations() {
  skipped 2 && return 0
  local f d n hit line target resolved rest window lo hi i

  # Pre-filter to the handful of lines that could possibly be a citation, so the
  # expensive per-line work runs on ~25 lines repo-wide rather than ~9000.
  while IFS= read -r f; do
    [ -n "$f" ] || continue
    d="$(dirname "$f")"
    while IFS= read -r hit; do
      n="${hit%%:*}"
      line="${hit#*:}"

      target="$(printf '%s\n' "$line" | grep -oE '`[A-Za-z0-9_./-]+\.md`' | head -1 | tr -d '`')"
      [ -n "$target" ] || continue
      if   [ -e "$d/$target" ]; then resolved="$d/$target"
      elif [ -e "$target" ];    then resolved="$target"
      else continue   # unresolvable path is check 1's finding, not this one
      fi
      grep -qE '^#{1,4} Step [0-9]+' "$resolved" || continue

      rest="${line#*"$target"\`}"
      window="${rest:0:40}"
      window="${window%%. *}"; window="${window%%;*}"; window="${window%%|*}"

      for i in $(printf '%s\n' "$window" \
                   | grep -oE '[Ss]teps? [0-9]+([^.0-9][^0-9]*[0-9]+)?' \
                   | grep -oE '[0-9]+([^0-9]+[0-9]+)?'); do
        lo="${i%%[!0-9]*}"
        hi="${i##*[!0-9]}"
        [ "$hi" = "$i" ] && hi="$lo"
        [ "$lo" -le "$hi" ] 2>/dev/null || continue
        for ((; lo <= hi; lo++)); do
          grep -qE "^#{1,4} Step $lo\b" "$resolved" \
            || finding 2 "$f:$n" "cites '$target Step $lo' but that file has no such step heading"
        done
      done
    done < <(grep -nE '\.md`[^|]{0,40}[Ss]tep' "$f" 2>/dev/null)
  done < <(_live_md)
}

# ---------------------------------------------------------------------------
# Check 3 -- frontmatter contract per artifact type.
#
# A skill missing `description` never triggers; a command missing it never shows
# a useful hint; an agent missing `model` inherits something unintended. All six
# skills, thirteen commands and four agents already conform, so this is a
# ratchet against regression rather than a migration.
#
# `version` is asserted semver because release-please owns the PLUGIN version
# while skill versions are hand-maintained (CLAUDE.md § Versioning) -- the hand-
# maintained ones are precisely the ones that can drift into nonsense.
# ---------------------------------------------------------------------------
check_frontmatter() {
  skipped 3 && return 0
  local f fm key

  _fm() { sed -n '/^---$/,/^---$/p' "$1"; }
  _has() { printf '%s\n' "$1" | grep -qE "^$2:"; }

  while IFS= read -r f; do
    [ -n "$f" ] || continue
    fm="$(_fm "$f")"
    [ -n "$fm" ] || { finding 3 "$f" "no YAML frontmatter"; continue; }
    for key in name description status version; do
      _has "$fm" "$key" || finding 3 "$f" "skill frontmatter missing '$key'"
    done
    if _has "$fm" version; then
      printf '%s\n' "$fm" | grep -qE '^version: *[0-9]+\.[0-9]+\.[0-9]+ *$' \
        || finding 3 "$f" "skill 'version' is not semver (x.y.z)"
    fi
  done < <(git -C "$ROOT" ls-files 'skills/*/SKILL.md')

  while IFS= read -r f; do
    [ -n "$f" ] || continue
    fm="$(_fm "$f")"
    [ -n "$fm" ] || { finding 3 "$f" "no YAML frontmatter"; continue; }
    for key in description argument-hint; do
      _has "$fm" "$key" || finding 3 "$f" "command frontmatter missing '$key'"
    done
  done < <(git -C "$ROOT" ls-files 'commands/*.md')

  while IFS= read -r f; do
    [ -n "$f" ] || continue
    fm="$(_fm "$f")"
    [ -n "$fm" ] || { finding 3 "$f" "no YAML frontmatter"; continue; }
    for key in name description model; do
      _has "$fm" "$key" || finding 3 "$f" "agent frontmatter missing '$key'"
    done
  done < <(git -C "$ROOT" ls-files 'agents/*.md')
}

# ---------------------------------------------------------------------------
# Check 4 -- a skill whose content changed also moved its version.
#
# Diff-aware, so it only runs with --base. Skill versions are hand-maintained
# and unrelated to the release-please-owned plugin version, which means the only
# thing that has ever moved them is somebody remembering. In #166 that somebody
# was a checklist item; this makes it a gate.
#
# Frontmatter-only changes (e.g. the version bump itself) do not require a
# further bump, or the check would demand a second bump for the first one.
# ---------------------------------------------------------------------------
check_version_bump() {
  skipped 4 && return 0
  [ -n "$BASE" ] || return 0
  local changed skill sk before after body_changed

  # A skill is its whole directory, not just SKILL.md. Fixing a broken load path
  # in references/ changes what the skill does at runtime exactly as much as
  # editing SKILL.md does, and scoping this check to SKILL.md would have let this
  # very PR touch four references/ files without moving a single version.
  changed="$(git -C "$ROOT" diff --name-only "$BASE" -- 'skills/*/**' 'skills/*/*' 2>/dev/null \
               | grep -v '^skills/shared/' | cut -d/ -f1-2 | sort -u)"

  while IFS= read -r skill; do
    [ -n "$skill" ] || continue
    sk="$skill/SKILL.md"
    [ -f "$ROOT/$sk" ] || continue
    git -C "$ROOT" cat-file -e "$BASE:$sk" 2>/dev/null || continue   # newly added skill

    # A frontmatter-only diff on SKILL.md is usually the bump itself; requiring a
    # further bump for it would never terminate. But a references/ change is a
    # body change by definition, so treat any non-SKILL.md diff as body-changed.
    body_changed=0
    if git -C "$ROOT" diff --name-only "$BASE" -- "$skill" 2>/dev/null | grep -qv "^$sk$"; then
      body_changed=1
    elif ! diff -q \
        <(git -C "$ROOT" show "$BASE:$sk" | sed '/^---$/,/^---$/d') \
        <(sed '/^---$/,/^---$/d' "$ROOT/$sk") >/dev/null 2>&1; then
      body_changed=1
    fi
    [ "$body_changed" = 1 ] || continue

    before="$(git -C "$ROOT" show "$BASE:$sk" | grep -m1 -E '^version:' || true)"
    after="$(grep -m1 -E '^version:' "$ROOT/$sk" || true)"
    [ "$before" = "$after" ] \
      && finding 4 "$sk" "content under $skill/ changed since $BASE but 'version' is unchanged ($after)"
  done <<< "$changed"
}

# ---------------------------------------------------------------------------
# Check 5 -- a referenced slash command exists, or is a TRACKED forward reference.
#
# #166 deliberately points at /holacracy:process-tension, which does not exist.
# That was honest -- the alternative was to quietly widen triage's scope to fill
# the gap, which is the exact conflation the PR existed to undo. But an honest
# forward reference and a stale one are indistinguishable six months later.
#
# So: forward references are allowed, and must be declared in
# evals/forward-references.txt with an OPEN issue number. When the issue closes,
# this check goes red -- either the command shipped and the entry is stale, or
# the reference has outlived its plan. Either way somebody looks. That turns
# vapour into debt with an expiry date.
# ---------------------------------------------------------------------------
check_command_refs() {
  skipped 5 && return 0
  local ref name entry issue state

  while IFS= read -r ref; do
    [ -n "$ref" ] || continue
    name="${ref#/holacracy:}"
    [ -f "$ROOT/commands/$name.md" ] && continue

    entry="$(grep -E "^${ref}[[:space:]]" "$ROOT/evals/forward-references.txt" 2>/dev/null | head -1)"
    if [ -z "$entry" ]; then
      finding 5 "evals/forward-references.txt" \
        "$ref is referenced in prose but commands/$name.md does not exist, and it is not declared a forward reference"
      continue
    fi
    issue="$(printf '%s\n' "$entry" | grep -oE '#[0-9]+' | head -1)"
    if [ -z "$issue" ]; then
      finding 5 "evals/forward-references.txt" "$ref is declared but carries no tracking issue"
      continue
    fi
    # Issue state is verified by CI where `gh` is authenticated; locally the
    # declaration alone is accepted so the lint stays runnable offline.
    if command -v gh >/dev/null 2>&1 && [ -n "${SKILLS_LINT_CHECK_ISSUES:-}" ]; then
      state="$(gh issue view "${issue#\#}" --json state --jq .state 2>/dev/null || echo UNKNOWN)"
      [ "$state" = "CLOSED" ] && finding 5 "evals/forward-references.txt" \
        "$ref is declared against $issue, which is now CLOSED -- ship the command or drop the reference"
    fi
  done < <(_shipped_md | xargs grep -ohE '/holacracy:[a-z0-9:-]+' 2>/dev/null \
             | sed 's/[^a-z0-9:-]*$//' | sort -u)
}

# ---------------------------------------------------------------------------
# Check 6 -- every shared reference has at least one caller.
#
# skills/shared/ is load-bearing by construction: nothing there is a leaf, and a
# file nobody loads is either dead weight or evidence that a rename dropped a
# caller silently. Ten files, all currently cited between 2 and 30 times.
# ---------------------------------------------------------------------------
# One grep over the corpus collecting every shared-reference basename that is
# mentioned anywhere, then set arithmetic -- rather than a full-corpus grep per
# shared file, which was O(files x shared) and the other half of the 45s.
check_orphans() {
  skipped 6 && return 0
  local f b mentioned
  mentioned="$(_shipped_md | grep -v '^skills/shared/' \
                 | tr '\n' '\0' | xargs -0 grep -ohoE '[a-z0-9-]+\.md' 2>/dev/null | sort -u)"
  for f in "$ROOT"/skills/shared/*.md; do
    [ -e "$f" ] || continue
    b="$(basename "$f")"
    printf '%s\n' "$mentioned" | grep -qxF "$b" \
      || finding 6 "skills/shared/$b" "no file loads this shared reference"
  done
}

# ---------------------------------------------------------------------------
# Check 7 -- a file that names the role-roster call also cites the procedure.
#
# `skills/shared/actor-and-role-resolution.md` Step 2 is the ONLY place allowed
# to say how the roster is loaded, because loading it wrong costs the turn:
# `glassfrog_list_my_roles` defaults to per_page 100 at ~1.5 KB per role, and
# `glassfrog_get_me(include_roles: true)` returned 124,801 characters for one
# real actor and was rejected outright (#148).
#
# This is the THIRD recurrence of one pattern -- a constraint documented
# ADJACENT to where it is needed rather than IN it. Before #148 the roster's
# size was recorded in ADR-0004, in a solutions doc, and in
# inherited-context-procedure.md, and still not in the procedure anyone
# follows, so every session rediscovered the limit by hitting it. #155 then
# found twelve files carrying the unbounded two-step inline. Prose in CLAUDE.md
# asking people to remember is the weakest enforcement that exists, which is
# the argument this script's own header makes.
#
# The rule is deliberately weaker than "only the canonical file may mention the
# tool". Naming both calls beside a pointer is the established house style --
# `commands/review-project.md` reads "Follow ... Steps 1-2: `glassfrog_get_me`,
# then `glassfrog_list_my_roles`" and that is good writing, not a violation.
# What must not exist is a file that prescribes the load with no pointer at all,
# because that is the copy that drifts. So: mention the tool, cite the
# procedure. A frontmatter `tools:` line is exempt -- it grants a capability
# rather than describing a call.
# ---------------------------------------------------------------------------
check_roster_delegation() {
  skipped 7 && return 0
  local f canon body
  canon="skills/shared/actor-and-role-resolution.md"
  while IFS= read -r f; do
    [ -n "$f" ] || continue
    [ "$f" = "$canon" ] && continue
    # Drop frontmatter tools: lines before looking for the call.
    body="$(grep -n 'glassfrog_list_my_roles' "$ROOT/$f" 2>/dev/null | grep -v '^[0-9]*:tools:')"
    [ -n "$body" ] || continue
    grep -q 'actor-and-role-resolution' "$ROOT/$f" 2>/dev/null && continue
    finding 7 "$f" "names glassfrog_list_my_roles but never cites $canon -- delegate to its Steps 1-2 instead of restating the call shape"
  done <<< "$(_live_md)"
}

check_links
check_step_citations
check_frontmatter
check_version_bump
check_command_refs
check_orphans
check_roster_delegation

if [ "$FINDINGS" -gt 0 ]; then
  printf '\nskills-lint: %d finding(s)\n' "$FINDINGS"
  exit 1
fi
printf 'skills-lint: clean\n'
